# Generated by Django 4.2.5 on 2023-11-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='teacher',
        ),
    ]
