# Generated by Django 4.2.5 on 2023-11-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_student_email_address_student_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email_address',
            field=models.EmailField(default='none@forgot.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='No Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='No Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email_address',
            field=models.EmailField(default='none@forgot.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default='No Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default='No Name', max_length=50),
        ),
    ]
