# Generated by Django 4.2.5 on 2023-11-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_dayofweek_level_classgroup_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(default='Enter Name', max_length=50),
        ),
    ]
