# Generated by Django 4.2.5 on 2023-11-20 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_level_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.classgroup'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classsession',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
