# Generated by Django 4.2.5 on 2023-11-20 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_classsession_class_group_classsession_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
