# Generated by Django 4.2.5 on 2023-11-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendance_class_session_attendance_is_present_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classgroup',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='classgroup',
            name='day_of_week',
            field=models.ManyToManyField(blank=True, to='attendance.dayofweek'),
        ),
    ]
