# Generated by Django 4.2.5 on 2023-12-05 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_alter_classgroup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classgroup',
            name='name',
        ),
    ]
